const data = [
  {
    id: 1,
    name: "John Doe",
    description: "Cool design",
    image: "/images/1.png",
  },
  {
    id: 2,
    name: "John Doe",
    description: "Cool design",
    image: "/images/2.png",
  },
  {
    id: 3,
    name: "John Doe",
    description: "Cool design",
    image: "/images/3.png",
  },
  {
    id: 4,
    name: "John Doe",
    description: "Cool design",
    image: "/images/4.png",
  },
  {
    id: 5,
    name: "John Doe",
    description: "Cool design",
    image: "/images/5.png",
  },
  {
    id: 6,
    name: "John Doe",
    description: "Cool design",
    image: "/images/6.png",
  },
  {
    id: 7,
    name: "John Doe",
    description: "Cool design",
    image: "/images/1.png",
  },
  {
    id: 8,
    name: "John Doe",
    description: "Cool design",
    image: "/images/2.png",
  },
  {
    id: 9,
    name: "John Doe",
    description: "Cool design",
    image: "/images/3.png",
  },
  {
    id: 10,
    name: "John Doe",
    description: "Cool design",
    image: "/images/4.png",
  },
  {
    id: 11,
    name: "John Doe",
    description: "Cool design",
    image: "/images/5.png",
  },
  {
    id: 12,
    name: "John Doe",
    description: "Cool design",
    image: "/images/6.png",
  },
  {
    id: 1,
    name: "John Doe",
    description: "Cool design",
    image: "/images/1.png",
  },
  {
    id: 2,
    name: "John Doe",
    description: "Cool design",
    image: "/images/2.png",
  },
  {
    id: 3,
    name: "John Doe",
    description: "Cool design",
    image: "/images/3.png",
  },
  {
    id: 4,
    name: "John Doe",
    description: "Cool design",
    image: "/images/4.png",
  },
  {
    id: 5,
    name: "John Doe",
    description: "Cool design",
    image: "/images/5.png",
  },
  {
    id: 6,
    name: "John Doe",
    description: "Cool design",
    image: "/images/6.png",
  },
  {
    id: 7,
    name: "John Doe",
    description: "Cool design",
    image: "/images/1.png",
  },
  {
    id: 8,
    name: "John Doe",
    description: "Cool design",
    image: "/images/2.png",
  },
  {
    id: 9,
    name: "John Doe",
    description: "Cool design",
    image: "/images/3.png",
  },
  {
    id: 10,
    name: "John Doe",
    description: "Cool design",
    image: "/images/4.png",
  },
  {
    id: 11,
    name: "John Doe",
    description: "Cool design",
    image: "/images/5.png",
  },
  {
    id: 12,
    name: "John Doe",
    description: "Cool design",
    image: "/images/6.png",
  },
  {
    id: 1,
    name: "John Doe",
    description: "Cool design",
    image: "/images/1.png",
  },
  {
    id: 2,
    name: "John Doe",
    description: "Cool design",
    image: "/images/2.png",
  },
  {
    id: 3,
    name: "John Doe",
    description: "Cool design",
    image: "/images/3.png",
  },
  {
    id: 4,
    name: "John Doe",
    description: "Cool design",
    image: "/images/4.png",
  },
  {
    id: 5,
    name: "John Doe",
    description: "Cool design",
    image: "/images/5.png",
  },
  {
    id: 6,
    name: "John Doe",
    description: "Cool design",
    image: "/images/6.png",
  },
  {
    id: 7,
    name: "John Doe",
    description: "Cool design",
    image: "/images/1.png",
  },
  {
    id: 8,
    name: "John Doe",
    description: "Cool design",
    image: "/images/2.png",
  },
  {
    id: 9,
    name: "John Doe",
    description: "Cool design",
    image: "/images/3.png",
  },
  {
    id: 10,
    name: "John Doe",
    description: "Cool design",
    image: "/images/4.png",
  },
  {
    id: 11,
    name: "John Doe",
    description: "Cool design",
    image: "/images/5.png",
  },
  {
    id: 12,
    name: "John Doe",
    description: "Cool design",
    image: "/images/6.png",
  },
  {
    id: 1,
    name: "John Doe",
    description: "Cool design",
    image: "/images/1.png",
  },
  {
    id: 2,
    name: "John Doe",
    description: "Cool design",
    image: "/images/2.png",
  },
  {
    id: 3,
    name: "John Doe",
    description: "Cool design",
    image: "/images/3.png",
  },
  {
    id: 4,
    name: "John Doe",
    description: "Cool design",
    image: "/images/4.png",
  },
  {
    id: 5,
    name: "John Doe",
    description: "Cool design",
    image: "/images/5.png",
  },
  {
    id: 6,
    name: "John Doe",
    description: "Cool design",
    image: "/images/6.png",
  },
  {
    id: 7,
    name: "John Doe",
    description: "Cool design",
    image: "/images/1.png",
  },
  {
    id: 8,
    name: "John Doe",
    description: "Cool design",
    image: "/images/2.png",
  },
  {
    id: 9,
    name: "John Doe",
    description: "Cool design",
    image: "/images/3.png",
  },
  {
    id: 10,
    name: "John Doe",
    description: "Cool design",
    image: "/images/4.png",
  },
  {
    id: 11,
    name: "John Doe",
    description: "Cool design",
    image: "/images/5.png",
  },
  {
    id: 12,
    name: "John Doe",
    description: "Cool design",
    image: "/images/6.png",
  },
];

export { data };
